config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "contents#index"
  resources :contents do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: 'HTML'},
    { id: 3, name: 'CSS'},
    { id: 4, name: 'Ruby'},
    { id: 5, name: 'JavaScript'},
    { id: 6, name: 'C#'},
    { id: 7, name: 'PHP'},
    { id: 8, name: 'Python'},
    { id: 9, name: 'Java'},
    { id: 10, name: 'SQL'},
    { id: 11, name: 'その他'}
  ]
  include ActiveHash::Associations
  has_many :contents
end

app/models/content.rb
class Content < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
  validates :category_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :images, length: { minimum: 0, maximum: 3, message: "は3枚以下にしてください" }

  belongs_to :user
  has_many_attached :images
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  def self.search(search)
    if search != ""
      Content.where('title LIKE(?)', "%#{search}%")
    else
      Content.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :edit, :search]

  def index
    content_extract
  end
  
  def new
    @content = Content.new
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @content = Content.find(params[:id])
    content_extract
  end

  def edit
    @content = Content.find(params[:id])
    if @content.user_id != current_user.id
      redirect_to root_path
    end
  end

  def update
    @content = Content.find(params[:id])
    if @content.update(content_params)
      redirect_to content_path(@content.id)
    else
      render :edit
    end
  end
  

  def destroy
    @content = Content.find(params[:id])
    if @content.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @search = Content.search(params[:keyword])
    @category = Category.all 
    @contents = @search.where(user_id: current_user.id)
    @user_content = []
    @category.each do |num|
      @user_content << instance_variable_set('@c'+(num.id).to_s, @contents.where(category_id: num.id))
    end
  end

  private

    def content_params
      params.require(:content).permit(:title, :text, :category_id, {images: []}).merge(user_id: current_user.id)
    end

    def content_extract
      if user_signed_in? #ユーザーログイン時のみ、ユーザーに結びついた記事をカテゴリー別に取得、表示するためのインスタンスを生成する
        @category = Category.all 
        @contents = Content.where(user_id: current_user.id)
        @user_content = []
        @category.each do |num|
          @user_content << instance_variable_set('@c'+(num.id).to_s, @contents.where(category_id: num.id))
        end
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
  
  require 'uri'
  def text_url_to_link text

    URI.extract(text, ['http','https'] ).uniq.each do |url|
      sub_text = ""
      sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"
  
      text.gsub!(url, sub_text)
    end
  
    return text
  end

  def escape_dissable text
    text = text.gsub(/&it;|&anp;|&gt;/, "&it;" => "<", "&anp;" => "&", "&gt;" => ">")
    return text
  end

end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/edit.html.erb
<%= render "shared/header2"%>
<div class='account-page2' id='account-page'>
  <div class='account-page__inner2 clearfix'>
    <div class='account-page__inner--left2 account-page__header2'>
      <h2 class="content-ac-eng">Edit Content</h2>
      <h5 class="content-ac-jpn">記事を編集する</h5>
    </div>
    <div class='account-page__inner--right2 user-form'>
      <%= form_with model: @content, id: 'new_post', local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
        <div class='field2'>
          <div class='field-label2'>
            <%= f.label :title, {class:"title-label"} %>
          </div>
          <div class='field-input2'>
            <%= f.text_field :title, class:"title", placeholder:"タイトル", autofocus: true%>
          </div>
        </div>
        <div class='field2'>
          <div class='field-label2'>
            <%= f.label :text, {class:"text-label"} %>
          </div>
          <div class='field-input2'>
            <%= f.text_area :text, class:"text", placeholder:"テキスト" %>
          </div>
        </div>
       <div>
          <div id="previews" class="images-box"></div>
          <div class="click-upload">
            <p class="click-message">クリックしてファイルをアップロード(3枚まで)</p>
            <%= f.file_field :image, name: 'content[images][]', data: {index: 0} %>
          </div>
        </div>
        <div class='field2'>
          <div class='field-label2'>
            <%= f.label :category_id, {class:"category-label"} %>
          </div>
          <div class='field-input2'>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
          </div>
        </div>
 
        <div class='actions2'>
          <%= f.submit "Edit Content", class: 'btn2'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/contents/index.html.erb
<%= render "shared/header"%>
<div class="wrapper">
  <div class="sb">
  <%= render "shared/side_bar" %>
  </div>
  <div class="cv">
  <%= render "shared/contents_view" %>
  </div>
</div>

app/views/contents/new.html.erb
<%= render "shared/header2"%>
<div class='account-page2' id='account-page'>
  <div class='account-page__inner2 clearfix'>
    <div class='account-page__inner--left2 account-page__header2'>
      <h2 class="content-ac-eng">Create Content</h2>
      <h5 class="content-ac-jpn">記事を作成する</h5>
    </div>
    <div class='account-page__inner--right2 user-form'>
      <%= form_with model: @content, id: 'new_post', local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
        <div class='field2'>
          <div class='field-label2'>
            <%= f.label :title, {class:"title-label"} %>
          </div>
          <div class='field-input2'>
            <%= f.text_field :title, class:"title", placeholder:"タイトル", autofocus: true%>
          </div>
        </div>
        <div class='field2'>
          <div class='field-label2'>
            <%= f.label :text, {class:"text-label"} %>
          </div>
          <div class='field-input2'>
            <%= f.text_area :text, class:"text", placeholder:"テキスト" %>
          </div>
        </div>
       <div>
          <div id="previews" class="images-box"></div>
          <div class="click-upload">
            <p class="click-message">クリックしてファイルをアップロード(3枚まで)</p>
            <%= f.file_field :image, name: 'content[images][]', data: {index: 0} %>
          </div>
        </div>
        <div class='field2'>
          <div class='field-label2'>
            <%= f.label :category_id, {class:"category-label"} %>
          </div>
          <div class='field-input2'>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
          </div>
        </div>
 
        <div class='actions2'>
          <%= f.submit "Create Content", class: 'btn2'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/contents/search.html.erb
<%= render "shared/header"%>
<div class="wrapper">
  <div class="sb">
  <%= render "shared/side_bar" %>
  </div>
  <div class="cv">
  <%= render "shared/contents_view" %>
  </div>
</div>

app/views/contents/show.html.erb
<%= render "shared/header"%>
<div class="wrapper">
  <div class="sb">
  <%= render "shared/side_bar" %>
  </div>
  <div class="cv">
  <%= render "shared/contents_view" %>
  </div>
</div>

app/views/contents/show.js.erb
$(".cv").html("<%= escape_javascript(render 'shared/contents_view', show: @content) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" ref="reset.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_contents_view.html.erb
<div class="contents-back">

  <% if user_signed_in?%>

    <% if @content.present?%>
      <div class="main-contents">
        <div class="main-title">
          <%= @content.title %>
        </div>
        <% if @content.images.attached?%>
          <div class="main-image">
                <% @content.images[0..-1].each do |image| %>
                  <div class="content-images">
                    <%= image_tag image.variant(resize: '300x300'), class: 'content-image' %>
                  </div>
                <%end%>
          </div>
        <% end %>
        <div class="main-text">
          <%= text_url_to_link(escape_dissable(safe_join((h(@content.text)).split("\n"),tag(:br)))).html_safe %>
        </div>
        <div class="contents-bottom">
          <%= link_to "編集", edit_content_path(@content.id), class: "edit-button"%>
          <%= link_to "削除", content_path(@content.id), method: :delete, class: "destroy-button"%>
        </div>
      </div>
    <% else %>
       <div class="main-contents">
          <div class="main-title">
            ようこそSlatへ
          </div>
          <div class="main-text">
            <h3>＜概要＞<br></h3>
            ・このアプリは、増えるブックマークや知識を記事という形でアウトプットすることで整理するものです。<br>
            <h3>＜記事の作成方法＞<br></h3>
            ・記事を作成する場合は、ヘッダーの記事作成ボタンより記事を作成してください<br>
            ・記事作成時、画像は任意で3枚まで付けることができますが、herokuの標準機能では24時間経過で自動的に表示されなくなります。<br>
            ・テキスト欄にはURLをそのまま載せることが可能、段落もそのまま本文に反映されます。<br>
            <h3>＜記事の閲覧方法＞<br></h3>
            ・画面左側のサイドバーにあなたが作成した記事カテゴリーを表示します。（他ユーザーの記事は表示されません）<br>
            ・カテゴリーをクリックすることで、そのカテゴリーの記事名を一覧表示、再クリックで収納します。<br>
            ・記事名をクリックすることで、記事の詳細を確認出来ます。<br>
            <h3>＜記事の編集＞<br></h3>
            ・記事画面の下の編集ボタンより編集画面に入れます。<br>
            <h3>＜記事の削除＞<br></h3>
            ・記事画面の下の削除ボタンより削除出来ます。現状、確認ボタンが出てきたりはしないので誤って削除しないように注意してください。<br>
            <h3>＜記事名の検索＞<br></h3>
            ・ヘッダーにある検索フォームで検索したい言葉を入れてボタンを押すことで、入力した文字を含む記事名のみに絞り込むことが可能です。<br>
          </div>
        </div>
    <% end %>
  <% else %>
    <div class="main-contents">
      <div class="main-title">
      ようこそSlatへ
      </div>
      <div class="main-text">
      ここは自分の知識を整理する空間です。<br>
      初めての方は新規登録ボタン、既にアカウント登録されている方はログインボタンを押してください。<br>
      </div>
    </div>
  <% end %>

</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<div class="header-back">
  <div class="header-left">
    <%= link_to root_path, class: "logo" do%>
    <%= image_tag 'Slat.png', class: "logo-image" %>
    <% end %>

    <% if user_signed_in? %>
      <div class="search-form">
        <%= form_with url: search_contents_path, method: :get, local: true do |f| %>
          <%= f.text_field :keyword, placeholder: "記事名を検索する"%>
          <%= f.submit "検索", id: "search-btn" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="header-right">

    <% if user_signed_in? %>
      <div class="user-name">
      ようこそ<%=current_user.nickname%>さん
      </div>
    <% else %>
      <div class="user-name">
      </div>
    <% end %>

    <% if user_signed_in? %>
      <div class="action-button">
        <%= link_to "記事作成", new_content_path, class: "content-create", id: "content-create-btn"%>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout", id: "logout-btn"%>
      </div>
    <% else %>
      <div class="action-button">
        <%= link_to "ログイン", new_user_session_path, class: "login", id: "login-btn"%>
        <%= link_to "新規登録", new_user_registration_path, class: "sign-up", id: "sign-up-btn"%>
      </div>
    <% end %>
  </div>

</div>

app/views/shared/_header2.html.erb
<div class="header-back">
  <div class="header-left">
    <%= link_to root_path, class: "logo" do%>
    <%= image_tag 'Slat.png', class: "logo-image" %>
    <% end %>
  </div>

  <div class="header-right">

    <% if user_signed_in? %>
      <div class="user-name">
      ようこそ<%=current_user.nickname%>さん
      </div>
    <% else %>
      <div class="user-name">
      </div>
    <% end %>

    <% if user_signed_in? %>
      <div class="action-button">
        <%= link_to "記事作成", new_content_path, class: "content-create", id: "content-create-btn"%>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout", id: "logout-btn"%>
      </div>
    <% else %>
      <div class="action-button">
        <%= link_to "ログイン", new_user_session_path, class: "login", id: "login-btn"%>
        <%= link_to "新規登録", new_user_registration_path, class: "sign-up", id: "sign-up-btn"%>
      </div>
    <% end %>
  </div>

</div>

app/views/shared/_side_bar.html.erb
<div class="side-back">


  <% if user_signed_in? %>
    <%@user_content.each do |content|%>
      <% if content.present? %>
        <div class=category-list>
          <div class="category-title" type="disc">
            <div class="category-name">【<%= content.first.category.name %>】</div>
            <ul class="contents-side-box">
              <% content.each do |t| %>
                <li class="title-list"> <%= link_to t.title, content_path(t.id), class: "content-title", remote: true %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>

  <% else %>
    <div class=category-list>
      <div class="category-title" type="disc">
        <div class="category-name">【サンプルカテゴリー】</div>
          <ul class="contents-side-box">
            <li class="title-list"><div class="content-title">サンプルコンテンツ1</div></li>
            <li class="title-list"><div class="content-title">サンプルコンテンツ2</div></li>
          </ul>
        </div>
      </div>
  <% end %>
</div>